### ISSUE TITLE
Can I use a git-sync container as an initContainer instead of sidecar?

### ISSUE THREAD

**Issue by luckymagic7** [kubernetes/git-sync#127]
Hi again!

This is my pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: syncrepo-volume-pod-test
spec:
  containers:
  - image: alpine
    name: test
    volumeMounts:
    - name: git-source
      mountPath: /tmp/git
  initContainers:
  - image: k8s.gcr.io/git-sync:v3.0.1
    name: git-data
    volumeMounts:
    - name: git-source
      mountPath: /tmp/git
    env:
    - name: GIT_SYNC_REPO
      value: https://gitlab.privatedomain.com/myrepo.git
    - name: GIT_SYNC_BRANCH
      value: production
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_DEST
      value: git-sync
    - name: GIT_SYNC_USERNAME
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: username
    - name: GIT_SYNC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: password
  volumes:
  - name: git-source
    emptyDir: {}
```

I successfully create a Pod, but the `git-data` initContainer doesn't exit.
` kubectl describe pod syncrepo-volume-pod-test`:
```
Name:         syncrepo-volume-pod-test
Namespace:    default
.
.
.
Init Containers:
  git-data:
    Container ID:   docker://a28da707768a4607e9f9b96d579a791fa2417356b90a3f7fac1372635522c929
    Image:          k8s.gcr.io/git-sync:v3.0.1
    Image ID:       docker-pullable://k8s.gcr.io/git-sync@sha256:fc4152d373e79ca680704713f7b748dd25f63f87b4a17c4edfd7bb7bc5a11be0
    Port:           <none>
    Host Port:      <none>
    State:          Running
.
.
.
```

I think the initContainer must exit after successfully proceed its command, and then the main container(in this case `test`) can run.

Can you please give me a hint?

Thanks! 😄
