### ISSUE TITLE
Enforcing 0400 permission on git ssh key has other security implications

### ISSUE THREAD

**Issue by willthames** [kubernetes/git-sync#129]
Because kubernetes secret volumes are mounted as owned by root, this means that if /etc/git-secret/ssh is mounted as a secret volume, to meet the 0400 permission requirement, the key is readable only by root. 

This means that the container needs to run as root, which is a bad practice (and might breach some PodSecurityPolicies) 

There is no amazing workaround for this - the [canonical discussion](https://github.com/kubernetes/kubernetes/issues/2630) suggests using fsGroups, which would work well, but would need 0440 permissions to be readable by a non-root user.

Could we have a flag that turns the permission checking off, or allows a more permissive permission ot be set?

**Comment by stp-ip** [comment]
This seems to work for me, not sure, which problem you are running into specifically.
```
      - name: git-secret
        secret:
          secretName: dns-origin
          defaultMode: 256
```

This runs with a securityContext like this:
```
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["all"]
```

**Comment by willthames** [comment]
@stp-ip, it would indeed run like that, but I really don't want to use `runAsUser: 0` if I can possibly avoid it - there are no other good reasons for the container to need to run as root, as far as I'm aware. 

Dropping all capabilities would definitely mitigate some of the issues running as root, but some PodSecurityPolicies disallow running as root at all.

**Comment by stp-ip** [comment]
Ah right sorry wrong config. There should be another one working without root. Will look it up in the coming days. Sorry for the mixup.

**Comment by pre** [comment]
@stp-ip do you have an example configuration which works without `runAsUser: 0` ?

**Comment by pre** [comment]
A workaround is an initContainer which copies files from a configmap volume to the local filesystem and then chowns them to the non-root owner ..

**Comment by mceg** [comment]
Because from 3.1 you can specify a different ssh key file, you can run container as non root by for example changing it to /tmp/ssh and then adding command:
```
command: ["sh", "-c", "cp /etc/git-secret/ssh /tmp/ssh && chown nobody:nobody /tmp/ssh && chmod 400 /tmp/ssh && /git-sync"]```

just don't mount it with `defaultMode: 256` as you won't be able to copy it in the command.

**Comment by thockin** [comment]
I spent a little time on this here's what I found.  It's incomplete but maybe a starting point.

1) ssh demands the current uid be in /etc/passwd.

2) if you run a 65534 (nobody) ssh runs, but it tries to make a .ssh dir.  It ignores $HOME and uses the homedir from /etc/passwd, which is /.  That fails to mkdir, obviously.

3) We could add a git-sync user and group with a non-root UID/GID and homedir of /tmp, to allow people to run as that (optional)

4) We need the secret as documented in this repo, but we need it to be mode 0600, rather than 0400

5) We need to set the fsgroup to the non-root GID

My cluster is somewhat busted right now (too many experiments) so something is still failing.  I am out of time for playing with this today.

**Comment by thockin** [comment]
Also git-sync needs to allow group-read perms on the key.  SSH is OK with it, but git-sync is not (patches welcome).

NB: I hacked and did not push an image with a new UID yet, but it seems to fly, maybe?  Here's my hacked up YAML:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git-sync
spec:
  selector:
    matchLabels:
      test: git-sync
  template:
    metadata:
      labels:
        test: git-sync
    spec:
      volumes:
      - name: git
        secret:
          secretName: git-creds
          defaultMode: 256 #0400
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.0
        # For debug enable this instead of args                                                                                                                                          
        #command: [ "sh", "-c", "sleep 10000" ]
        args:
         - "-ssh"
         - "-repo=git@github.com:thockin/git-sync"
         - "-dest=link"
         - "-branch=master"
         - "-depth=1"
         - "-wait=10"
         - "-v=5"
         - "-logtostderr"
        securityContext:
          runAsUser: 65534
        volumeMounts:
        - name: git 
          mountPath: /etc/git-secret
```

**Comment by willthames** [comment]
@thockin this works well for me with group read, but you do need to have a sensible securityContext at the pod level:

```
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - image: ...
```
