### ISSUE TITLE
git-sync ssh as an initContainer

### ISSUE THREAD

**Issue by PhilippeDupont** [kubernetes/git-sync#146]
Following https://github.com/kubernetes/git-sync/pull/144 : 

I don't want to force all volumes in the pod to be limited to user 65533, so how can we use it as an initContainer ?

**Comment by thockin** [comment]
They don't need to be limited to a user for the whole pod.  Each container can run as any user they want.  Setting the fsGroup should allow them all to read the git contents.

I don't have a demo of that, but it should work - does it not?

Alternately, you can run as an init container and manually chown/chmod if you want, but that requires more privilege.

**Comment by stp-ip** [comment]
Simplified example running in production:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git-sync-example
  namespace: tmp
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      project: example.git.sync
  template:
    metadata:
      labels:
        project: example.git.sync
    spec:
      securityContext:
        fsGroup: 65533
      containers:
      - name: example
        image: example/application:1.0.1
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["all"]
        args: [ "--conf=/etc/config.conf" ]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
            httpHeaders:
              - name: X-Probez
                value: readiness.k8s
          initialDelaySeconds: 120
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            httpHeaders:
              - name: X-Probez
                value: liveness.k8s
          initialDelaySeconds: 140
        ports:
          - name: health
            containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: source
          mountPath: /etc/source
      - name: git-sync
        image: thockin/git-sync:thtest #currently using our own build, but this test build is available from thockin
        securityContext:
          runAsUser: 65533
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["all"]
        volumeMounts:
        - name: source
          mountPath: /etc/source
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: git@gitlab.core:repo.git
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_WAIT
          value: "60"
        - name: GIT_SYNC_ROOT
          value: /etc/source/
        - name: GIT_SYNC_DEST
          value: files
      volumes:
      - name: config
        configMap:
          name: config
      - name: git-secret
        secret:
          secretName: git-secret
          defaultMode: 288
      - name: source
        emptyDir: {}

```

**Comment by thockin** [comment]
Maybe put that in a doc in this repo?  Would be nice if it ws actually
runnable (no "example app" images :)

Then we can close this?

**Comment by stp-ip** [comment]
Was an internal app so couldn't use it here. Can morph it into an example and push as docs. Might take a bit as I'm overloaded, but not forgotten.

**Comment by PhilippeDupont** [comment]
Thank you for your answers.

I still have an issue using the fsgroup : `ERROR: can't configure SSH: Permissions -r--r----- for SSH key are too open. It is recommended to mount secret volume with `defaultMode: 256` (decimal number for octal 0400).`

my deployment definition : 
```
[...]
    spec:
      initContainers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.0
          env:
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_REPO
              value: {{ .Values.persistentVolume.copyFromGithub.repo | quote }}
            - name: GIT_SYNC_ROOT
              value: "/app"
            - name: GIT_SYNC_DEST
              value: "backup"
          volumeMounts: 
            - name: "git-secret"
              mountPath: "/etc/git-secret"
[...]
          securityContext:
            runAsUser: 65533  # to allow read of ssh key
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["all"]
      containers:
[...]
      volumes:
[...]
      - name: git-secret
        secret:
          secretName: git-secret
          defaultMode: 288  
[...]
      securityContext:
        fsGroup: 65533
```

One another thing I can't figure out is that, changing the `defaultMode` to 256 again, create the exact same error.
I don't have the error when I remove the fsGroup. But got `fatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"`
