### ISSUE TITLE
Support for GitHub webhooks

### ISSUE THREAD

**Issue by paphillon** [kubernetes/git-sync#149]
Hi, thanks for this excellent neat project! I implemented and worked like a charm. However, it will be great if we can add GitHub webhooks support instead of polling to reduce the chattiness. Increasing the wait time helps, but then that would be the expected delay for the sync. With webhook the changes can be pulled instantaneous. 

The added complexity would be ingress routes, firewalls (if any), authentication to reach the end-point, might not be favorable in cloud deployment, but on-prem this should be pretty straightforward if using enterprise gitHub

**Comment by thockin** [comment]
I am not against seeing a design proposal, but truthfully I have no free time right now to implement this. :(

**Comment by paphillon** [comment]
@thockin - Unfornutalely I haven't picked up go yet, it's on my todo list for sure :). For now, I created a python flask wrapper over git-sync to add the webhook support. 
The design is pretty simple

* Expose two api's `/api/event/push` & '/api/heathz'
* The push api accepts the Git 'push' event payload and compares the branch in the `ref` key with the configured branch and git repo with the `ssl_url` proceeds to call git-sync command only if the above two matches. Few more checks like the event type is of only push and ping
* the healthz api returns the health of the container. However, it also checks for a bool flag that is set as true only if upon startup of Python flask the git-sync command was successful. This ensures that the git repo is synced upon startup of the pod
* The above api's have a configurable root context path that helps with the ingress setup

- Git config
* Select Repo --> Settings tab --> Hooks
* Add webhook
* Provide the hook URL (https://<ingress server - LB>/<hook context>/api/event/push)
* e.g. https://my.ingress.host.lb/grafana-sync/api/event/push
* Select Content type application/json
* Select 'Just the push event' (default)

Caveat - The git webhook should be only used if there is only one replica of pod, if there are two replica's the ingress will load balance the request and only one will receive the event and pods will be out of sync.

Let me know if you need more details, I will be happy to share the code.

**Comment by abh** [comment]
It doesn't seem worthwhile to have this feature without support for multiple replicas.

If a headless service is setup for git-sync it should be possible to relay the webhooks to the other instances relatively simply.

**Comment by paphillon** [comment]
@abh  - Good idea, let me give that a try.

**Comment by bewing** [comment]
Is there still an interest in this general feature?  As a learning experiment, I created a webhook fanout that uses an interface to determine which endpoints to fanout to -- a plugin that keeps track of replica pods via the kubernetes API would be the next step to enable replicating external hooks to trigger syncs to all copies of a pod.  I'd be willing to invest the time if there was still interest.

https://github.com/bewing/webhook-fanout

**Comment by abh** [comment]
I’d use the “webhook to all replicas” feature…

**Comment by bewing** [comment]
Updated https://github.com/bewing/webhook-fanout with a Pod source that uses an Informer to identify pods based on selector labels as my weekend project.  May continue to improve if I find an actual use-case for my day job.  Did some basic local testing, and it appears to function with a basic container spec:
```
    spec:
      containers:
      - args:
        - -selector=app=nginx,release=nginx-1586548329
        - -targetPort=80
        - -namespace=default
        image: bewing/webhook-fanout:latest
        imagePullPolicy: IfNotPresent
        name: testfan
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

Not sure what current status is in interest in implementing Github webhooks -- I think ideally I'd follow the `kubernetes/external-dns` model and have a `providers` module that interfaces with upstreams to register webhooks.
