### ISSUE TITLE
Clone via SSH fails because of custom port

### ISSUE THREAD

**Issue by KarstenSiemer** [kubernetes/git-sync#150]
Hello,

first of all i'd like to thank everyone for putting all this work into this project.
I'd like to clone and update a private bitbucket repository via ssh (only option).
The problem is, that the bitbucket installation is only allowing connetions on port 8081.
This container has no option to use any other port than default.
Pr's for ssh-extra-args and GIT_SSH_COMMAND for setting such things seem to have been dropped.

When i change the entry point of the container to sleep and exec into it, i can clone my repo like this:
```
eval `ssh-agent -s`
ssh-add /etc/git-secret/ssh
cd /git
git clone ssh://git@xxxxxxxx:8081/organisation/repo.git
```

Using the entry point and it's setting, this is failing like this:
```
E0305 12:31:42.457689       1 main.go:294] error syncing repo: error running command: exit status 128: "Cloning into '/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

This is the yaml of my deployment:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: ""
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: helm-kustomize
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: grafana
    chart: ""
    heritage: ""
    release: ""
  name: gm-grafana
  namespace: system-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ""
      app.kubernetes.io/component: grafana
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/managed-by: helm-kustomize
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: grafana
      chart: ""
      heritage: ""
      release: ""
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ""
        app.kubernetes.io/component: grafana
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/managed-by: helm-kustomize
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: grafana
        chart: ""
        heritage: ""
        release: ""
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: gm-grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: gm-grafana
        image: somerepo/grafana/grafana:6.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
        name: grafana
        ports:
        - containerPort: 80
          name: service
          protocol: TCP
        - containerPort: 3000
          name: grafana
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsUser: 472
        volumeMounts:
        - mountPath: /var/lib/grafana/git
          name: git
        - mountPath: /etc/grafana/grafana.ini
          name: config
          subPath: grafana.ini
        - mountPath: /etc/grafana/ldap.toml
          name: ldap
          subPath: ldap.toml
        - mountPath: /var/lib/grafana
          name: storage
          subPath: null
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: config
          subPath: datasources.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/dashboardproviders.yaml
          name: config
          subPath: dashboardproviders.yaml
      - env:
        - name: GIT_SYNC_REPO
          value: git@xxxxxxxx:8081/organisation/repo.git
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_DEST
          value: repo
        - name: GIT_SYNC_ROOT
          value: /git
        image: k8s.gcr.io/git-sync:v3.1.1
        name: git-sync
        securityContext:
          runAsUser: 65533
        volumeMounts:
        - mountPath: /etc/git-secret
          name: git-secret
        - mountPath: /git
          name: git
      securityContext:
        fsGroup: 65533
      serviceAccountName: gm-grafana
      volumes:
      - emptyDir: {}
        name: git
      - name: git-secret
        secret:
          defaultMode: 288
          secretName: grafana-git-creds
      - configMap:
          name: gm-grafana
        name: config
      - name: ldap
        secret:
          items:
          - key: ldap-toml
            path: ldap.toml
          secretName: gm-grafana
      - name: storage
        persistentVolumeClaim:
          claimName: gm-grafana
```

I think because of the ":" notation inside the git url it is try to connect as user 8081 instead of using it as a port

Kubernetes version: v1.13.2
git-sync version: k8s.gcr.io/git-sync:v3.1.1

**Comment by seboudry** [comment]
Hi!
I've successfully use custom port on Git SSH URL (on a bitbucket server instance).
I've follow this doc https://github.com/kubernetes/git-sync/blob/master/docs/ssh.md and just configure some options.
Maybe the problem is not with port in URL but with mounted SSH credentials.

Here's testing configuration:
```yaml
spec:
  containers:
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.1.2
   command: ["/bin/sh", "-c"]
   args:
   - |
     echo "================= DIRECTORY /etc/git-secret/..data/"
     ls -la /etc/git-secret/..data/
     echo "================= SYNC"
     /git-sync
    env:
    - name: GIT_SYNC_REPO
      value: ssh://git@mygithost:7999/myproject/myrepo.git
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_SSH
      value: "true"
    - name: GIT_SSH_KEY_FILE
      value: /etc/git-secret/id_rsa
    securityContext:
      runAsUser: 65533 # git-sync user
    volumeMounts:
    - name: git-secret
      mountPath: /etc/git-secret
  volumes:
  - name: git-secret
    secret:
      secretName: git-secret
      defaultMode: 256 # 0400
```

Hope that helps.

**Comment by mcfearsome** [comment]
I am having a very similar issue.

We are using `git-sync` as in init container for kaniko in approximately 20 clusters.  Yesterday, with no changes to the job yaml we use, we started receiving this error, on a single cluster:
```
I0814 16:49:59.128777       1 main.go:270] starting up: ["/git-sync"]
E0814 16:50:08.392668       1 main.go:294] error syncing repo: error running command: exit status 128: "Cloning into '/tmp/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

I can inject a sleep into the init container and get on the pod and execute the commands the OP shared to clone the repo successfully, the key is correct, the known_hosts is correct, and I am a bit stuck on how to proceed with debugging.  

Here is my job yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: create-container
  namespace: qa-app
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: eks-pr-qa-kaniko
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --dockerfile=/context/container/Dockerfile.deploy
        - --context=/context/rev-d9127d5739803de9749418c13885b6417e0a3e23/
        - --destination={removed}
        - --build-arg=gem_server_creds=$(GEM_SERVER_CREDS)
        env:
        - name: GEM_SERVER_CREDS
          valueFrom:
            secretKeyRef:
              key: creds
              name: gem-creds
        image: gcr.io/kaniko-project/executor:latest
        imagePullPolicy: Always
        name: kaniko
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /context/
          name: data
        - mountPath: /kaniko/.docker/
          name: docker-config
        - mountPath: /context/container/config/env_qa_secrets.yml
          name: app-secret
          subPath: secrets.yml
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: GIT_SYNC_REPO
          value: {removed}
        - name: GIT_SYNC_BRANCH
          value: qa
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_DEST
          value: container
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_DEPTH
          value: "1"
        image: k8s.gcr.io/git-sync:v3.1.2
        imagePullPolicy: IfNotPresent
        name: git-sync
        resources: {}
        securityContext:
          runAsUser: 65533
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/git
          name: data
        - mountPath: /etc/git-secret
          name: git-secret
      - args:
        - /bin/sh
        - -c
        - echo 'RUN chown -R app:app /workarea' >> /context/container/Dockerfile.deploy
        image: busybox:latest
        imagePullPolicy: Always
        name: inject-chown
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /context/
          name: data
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65533
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: rails-env
      - name: git-secret
        secret:
          defaultMode: 288
          secretName: git-creds
      - configMap:
          defaultMode: 420
          name: docker-config
        name: docker-config
      - name: app-secret
        secret:
          defaultMode: 420
          secretName: app-qa-secrets
```

Any pointers on where to look would be appreciated.
