### ISSUE TITLE
SSH key Permission error

### ISSUE THREAD

**Issue by abergmeier** [kubernetes/git-sync#171]
On our OpenShift cluster, I get the following error:
```
ERROR: can't configure SSH: Permissions -r--r----- for SSH key are too open. It is recommended to mount secret volume with `defaultMode: 256` (decimal number for octal 0400).
```

Which seems strange because I have the following in the yaml:

```
volumes:
- name: git-secret
  secret:
    secretName: git-secret
    defaultMode: 256
```
