### ISSUE TITLE
git-sync doesn't work under arbitrary user

### ISSUE THREAD

**Issue by vkabanorv** [kubernetes/git-sync#176]
I'm trying to get the container to work under an arbitrary user ID, since this is a requirement in OpenShift depending on the cluster policies. I keep getting this error:

/git-sync -repo https://github.com/some-repo -username some-username -password *****
ERROR: can't create .netrc file: error setting up git credentials exit status 255: error: could not lock config file //.gitconfig: Permission denied

The usual course of action would be to make some files group-writable by the root group, but I can't understand what files I need to change - the /tmp directory is writable by any user and the .gitconfig file doesn't exist yet.

Would be grateful for any guidance!

**Comment by slowr** [comment]
Not sure if it helps or if its related but `git-sync` has uid 65533. In my case that we have a PSP policy that allow only uids of 1000-1500 I had to modify the image:
```
FROM k8s.gcr.io/git-sync:v3.1.2

USER 0:0

RUN sed -i "s/git-sync:x:65533:65533/git-sync:x:1000:1000/g" /etc/passwd

USER git-sync
```
and also needed to add a security context
```
      securityContext:
        fsGroup: 1000
```

**Comment by thockin** [comment]
@slowr The problem is that to exec SSH we have to have *something* in /etc/passwd.  I don't know why your policy is what it is, but certainly someone else has a different policy.  I a not sure how to resolve this generically.

@vkabanorv To be frank, I don't have a test case for username/password so I am not surprised it is broken.  Can you help me figure out how to add a test case to test_e2e.sh ?

**Comment by zoni** [comment]
Regarding the point raised by @slowr, I've found this can be resolved by simply mounting your own `/etc/passwd` file into the container with a UID of your choosing.

Relevant bits in case of Kubernetes (in this case forcing UID 3050):

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: git-sync-config
data:
  passwd: |
    root:x:0:0:root:/root:/bin/bash
    nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
    git-sync:x:3050:3050::/tmp:/sbin/nologin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  template:
    spec:
      securityContext:
        fsGroup: 3050
        runAsNonRoot: true
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.3
        args: [...]
        volumeMounts:
        - mountPath: /tmp/git
          name: workdir
        - mountPath: /etc/git-secret/
          name: git-secret
        - mountPath: /etc/passwd
          name: git-sync-config
          subPath: passwd
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 3050
          runAsGroup: 3050
      volumes:
      - name: git-sync-config
        configMap:
          name: git-sync-config
      - name: workdir
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: git-secret
          defaultMode: 288 # = mode 0440
```
