### ISSUE TITLE
Mount from another container with `volumeMounts.subPath` cause permission issue

### ISSUE THREAD

**Issue by akking** [kubernetes/git-sync#186]
Running `git-sync` as sidecar with another container mount the same volume but with `subPath` gives permission error when `git-sync` wants to delete the directory. eg:

With the main container mount the shared "dag-git" emptyDir.
```
volumeMounts:
- mountPath: /usr/local/airflow/dags
   name: dag-git
    readOnly: true
    subPath: git-sync/AirflowDags
```
When start the pod, `git-sync` throw error:

> I1003 19:25:16.405655       1 main.go:269]  "level"=0 "msg"="starting up"  "args"=["/git-sync"]
> I1003 19:25:16.406739       1 main.go:476]  "level"=0 "msg"="git root exists and is not empty (previous crash?), cleaning up"  "path"="/tmp/git"
> E1003 19:25:16.406911       1 main.go:294]  "msg"="failed to sync repo, aborting" "error"="unlinkat /tmp/git/git-sync/AirflowDags: permission denied"
