### ISSUE TITLE
Unable to run git-sync container in Kubernetes

### ISSUE THREAD

**Issue by prbsparx** [kubernetes/git-sync#201]
**Issue**
git-sync reports:
`standard_init_linux.go:207: exec user process caused "exec format error"`

**Steps to reproduce**
I cloned the GIT repo to my Mac.
Built it with:
`make container REGISTRY=registry.domain.com/project/git-sync VERSION=3.1.2 HTTP_PROXY=http://proxy-url:port HTTPS_PROXY=http://proxy-url:port`
Published it with:
`make push REGISTRY=registry.domain.com/project VERSION=3.1.2 TAG=3.1.2`

I then added the pushed docker image to a Rancher Kubernetes/Helm StatefulSet:
```
initContainers:
      - image: registry.domain.com/project/git-sync
        name: git-sync
        securityContext:
          runAsUser: 65533
        volumeMounts:
        - name: discourse-data
          mountPath: /bitnami/discourse/plugins/
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/jonmbake/discourse-ldap-auth.git
        - name: GIT_SYNC_ROOT
          value: /bitnami/discourse/plugins/
        - name: GIT_SYNC_DEST
          value: discourse-ldap-auth
        - name: GIT_SYNC_ONE_TIME
          value: "true"
```

Rancher is running on top of Ubuntu 16.04...
