### ISSUE TITLE
fail to deploy on k8s, occurs `No command specified`

### ISSUE THREAD

**Issue by youzipi** [kubernetes/git-sync#263]
I follow the demo's `deployment.yaml` and ssh config

but got error: `Error: Error response from daemon: No command specified`

after add `command: ["/bin/sh"]`,still not work, got error: `path not found xxx`

**it happened accidently**

my config file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      labels:
        name: blog
    spec:
      volumes:
        - name: code-dir
          emptyDir: {}
        - name: git-secret
          secret:
            secretName: git-creds
            defaultMode: 0400
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.6
          imagePullPolicy: IfNotPresent
#          command: ["/bin/sh"]
          env:
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SYNC_REPO
              value: "git@my-host/repo-name.git"
            - name: GIT_SYNC_BRANCH
              value: "dev"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "private"
            - name: GIT_SYNC_WAIT
              value: "60"
          volumeMounts:
            - name: code-dir
              mountPath: /git
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
          securityContext:
            runAsUser: 65533 # git-sync user
      securityContext:
        fsGroup: 65533 # to make SSH key readable
```

environment:
```
minikube=v1.12.3
kubernetes=v1.16.5
macOS=10.13.6
```
