### ISSUE TITLE
What ENV variable should be used to decrypt an SSH key

### ISSUE THREAD

**Issue by 030** [kubernetes/git-sync#306]
I would like to use a password protected SSH key. Would that be possible?

**Comment by thockin** [comment]
How do you plan to get the key into git-sync to open the key?

**Comment by 030** [comment]
I have created a secret and a mount:

```
          volumeMounts:
            - name: ssh-privatekey-known-hosts
              mountPath: /etc/git-secret
              readOnly: true
          env:
            - name: GIT_SYNC_REPO
              value: git@some-url.git
            - name: GIT_SYNC_SSH
              value: "true"
      volumes:
        - name: some-secret
          secret:
            secretName: some-secret
            items:
              - key: ssh-privatekey
                path: ssh
                mode: 0400
```
