### ISSUE TITLE
Deploy latest Laravel PHP code from Github

### ISSUE THREAD

**Issue by jasperf** [kubernetes/git-sync#316]
These are questions from someone coming from a [PHP Deployer](https://github.com/deployphp/deployer/) world where I use `dep deploy production` locally with PHP Deployer package installed to grab the latest repository code from Github chosen and push this to the production website. This using a simple config file in which we add a Laravel recipe, caching, repository, ssh native as choice,.. , number or releases and more. See `deploy.php` example below. 

What I am wondering about is how I can I
- deploy the latest master version from Github using Git Sync? Can I do this with a webhook and if so how? There is `GIT_SYNC_WEBHOOK_URL`, but it is not clear to me how this could be used / triggered from Github for example..
- If I want to do the update to the latest Github repo update from the container is that also possible and if so how? With a certain command perhaps? 

Here the deployment draft:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-data
  labels:
    tier: backend
  namespace: smt-local
spec:
  # autoscale using `kubectl autoscale deployment x --cpu-percent=50 --min=1 --max=10` instead of setting replicas
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # replicas: 2 
  selector:
    matchLabels:
      app: git-data
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: git-data
        tier: backend
    spec:
      containers:
        - name: git-data
          image: k8s.gcr.io/git-sync:v3.0.1
          # command: [ "sh", "-c", "ls /code/project" ]
          volumeMounts:
          - name: code-storage
            mountPath: /smt-local
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/smart48/smt-demo.git
          # - name: GIT_SYNC_ROOT
          #   value: /code
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEPTH
            value: "1"
          ## symlink directory
          - name: GIT_SYNC_DEST
            value: current
          # - name: GIT_SYNC_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: git-creds
          #       key: username
          # - name: GIT_SYNC_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: git-creds
          #       key: password
      volumes:
          - name: code-storage
            persistentVolumeClaim:
              claimName: code-pv-claim
```

Here the deployment script we use for a standard DO VPS setup:

```php
<?php

namespace Deployer;

require 'recipe/laravel.php';
require 'vendor/deployer/recipes/recipe/cachetool.php';

// Configuration
set('repository', 'git@github.com:user/app-v3.git');
set('default_stage', 'production');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
set('ssh_type', 'native');
set('cachetool', '/var/run/php/php7.4-fpm.sock');
set('keep_releases', 10);

// Make sure uploads & published , tls, logs aren't overwritten by deploying
set('shared_dirs', [
    'public/uploads',
    'public/published',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
]);
set('shared_files', [
    '.env',
    '.some_other_private_key',
]);
set('writable_dirs', [
    'public/uploads',
    'public/published',
    'storage/framework/cache/data',
    'storage/logs',
    'storage/tls',
    'storage/app/public',
]);

// CUSTOM DEPLOY COMMANDS
task('db:migrate', function () {
    run('cd {{release_path}} && php artisan migrate');
});
task('horizon:terminate', function () {
    run('cd {{release_path}} && php artisan horizon:terminate');
});

task('queue:restart', function() {
    run('cd {{release_path}} && php artisan queue:restart');
});

task('reload:php-fpm', function () {
run('sudo /etc/init.d/php7.4-fpm restart'); // Using SysV Init scripts
});


// Hosts
// dep deploy production
// dep deploy staging

   host('staging')
   ->hostname('staging.app.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('staging')
   ->set('deploy_path', '/home/forge/staging.app.com');

   host('production')
   ->hostname('app.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('production')
   ->set('deploy_path', '/home/forge/app.com');

   host('prodold')
   ->hostname('prod-w-1.app.com')
   ->user('forge')
   ->forwardAgent()
   ->stage('prodold')
   ->set('deploy_path', '/home/forge/app.com');

// Run database migrations
after('deploy:symlink', 'db:migrate');

// Restart job
after('db:migrate', 'queue:restart');

// Clear OPCache
after('queue:restart', 'cachetool:clear:opcache');
after('cachetool:clear:opcache', 'horizon:terminate');

after('deploy', 'reload:php-fpm');
after('rollback', 'reload:php-fpm');

```

### Update

Did find this inside https://github.com/kubernetes/git-sync/blob/release-3.x/test_e2e.sh so under a test shell file: 

```sh
##############################################
# Test branch syncing
##############################################
testcase "branch-sync"
BRANCH="$TESTCASE"--BRANCH
# First sync
git -C "$REPO" checkout -q -b "$BRANCH"
echo "$TESTCASE 1" > "$REPO"/file
git -C "$REPO" commit -qam "$TESTCASE 1"
git -C "$REPO" checkout -q master
GIT_SYNC \
    --wait=0.1 \
    --repo="file://$REPO" \
    --branch="$BRANCH" \
    --root="$ROOT" \
    --dest="link" \
    > "$DIR"/log."$TESTCASE" 2>&1 &
sleep 3
assert_link_exists "$ROOT"/link
assert_file_exists "$ROOT"/link/file
assert_file_eq "$ROOT"/link/file "$TESTCASE 1"
# Add to the branch.
git -C "$REPO" checkout -q "$BRANCH"
echo "$TESTCASE 2" > "$REPO"/file
git -C "$REPO" commit -qam "$TESTCASE 2"
git -C "$REPO" checkout -q master
sleep 3
assert_link_exists "$ROOT"/link
assert_file_exists "$ROOT"/link/file
assert_file_eq "$ROOT"/link/file "$TESTCASE 2"
# Move the branch backward
git -C "$REPO" checkout -q "$BRANCH"
git -C "$REPO" reset -q --hard HEAD^
git -C "$REPO" checkout -q master
sleep 3
assert_link_exists "$ROOT"/link
assert_file_exists "$ROOT"/link/file
assert_file_eq "$ROOT"/link/file "$TESTCASE 1"
# Wrap up
pass
```

Is this a webhook of sorts perhaps? Does not look like it and other example in the same file at least have `-webhook-url="http://127.0.0.1:$NCPORT" \` but again I am not seeing how to use this. We could we just use a shell script and only run this pod/container when we want to sync but that is not automated..

**Comment by jasperf** [comment]
Perhaps I can sync every now and then with `- "-wait=14400"` but that would not be a deployment when I have pushed to the repository either manually or automatically... unless it can wait and sync only if there has been an update?

P.S. Was reading https://tech.travelaudience.com/publishing-code-documentation-in-kubernetes-4afa7f7b6d58

**Comment by jasperf** [comment]
I can deploy

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-data
  labels:
    tier: backend
  namespace: smt-local
spec:
  # autoscale using `kubectl autoscale deployment x --cpu-percent=50 --min=1 --max=10` instead of setting replicas
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # replicas: 2 
  selector:
    matchLabels:
      app: git-data
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: git-data
        tier: backend
    spec:
      containers:
        - name: git-data
          image: k8s.gcr.io/git-sync:v3.0.1
          # command: [ "sh", "-c", "ls /code/project" ]
          volumeMounts:
          - name: code-storage
            mountPath: /code
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/smart48/smt-demo.git
          - name: GIT_SYNC_ROOT
            value: /code
          - name: GIT_SYNC_BRANCH
            value: master
          - name: GIT_SYNC_DEPTH
            value: "1"
          ## symlink directory
          - name: GIT_SYNC_DEST
            value: current
          # not one off syncing as we will deploy often
          - name: GIT_SYNC_ONE_TIME
            value: "0"
          # - name: GIT_SYNC_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: git-creds
          #       key: username
          # - name: GIT_SYNC_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: git-creds
          #       key: password
      volumes:
          - name: code-storage
            persistentVolumeClaim:
              claimName: code-pv-claim
```

and it works and finally stores in the correct volume and under the correct directory. But how can I deploy again without destroying the pod and doing it all again? The latter removes all revisions and that is not what I want of course.
