### ISSUE TITLE
Issue cloning from Github with SSH

### ISSUE THREAD

**Issue by ursuad** [kubernetes/git-sync#33]
Because of #32 I tried switching to SSH, but the container keeps crashing again. 

The logs are:
```
$ kubectl logs dp-analytics-blog-2fjnv -c git-sync
I0202 13:28:42.608581       1 main.go:162] starting up: ["/git-sync"]
E0202 13:28:43.307843       1 main.go:169] error syncing repo: error running command: exit status 128: "Cloning into '/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

Just to test, I replaced the container command with:
```
#        command: ["cat"]
#        args: ["/etc/git-secret/ssh"]
```
I got the SSH key from the output, removed all my local keys from the SSH agent, imported that key (from the container) with `ssh-add` and it worked to clone the repo.  So it must be something from the container?

My config:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc-name
spec:
  replicas: 1
  template:
    metadata:
      name: my-pod-name
      labels:
        application: my-app
        component: my-comp
        environment: my-env
    spec:
      containers:
      - name: git-sync
        image: gcr.io/google_containers/git-sync:v2.0.4
#        command: ["cat"]
#        args: ["/etc/git-secret/ssh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: "git@github.com:GITHUB_USER/GITHUB_REPO.git"
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEST
          value: git
        - name: GIT_SYNC_DEPTH
          value: "1"
      volumes:
      - name: html
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: github-secret-ssh
          defaultMode: 0400
```
