### ISSUE TITLE
non zero return code not respected inside kubernetes pod init container

### ISSUE THREAD

**Issue by cforce** [kubernetes/git-sync#339]
I am running the image as kubernetes pod init container, which seems to be even return 0 (success) if the git-sync fails with non zero return codes.
From pods descrive status section
  ```
- containerID: docker://55c2100d7a11b2e3c9bce8daacabd5b2b75257cb0fe189857b70e82e95645b43
    image: XXXXXXXXXXXXXX/git-sync:v3.2.2
    imageID: docker-pullable://XXXXXXXXXXXXXXXX/git-sync@sha256:85d203d29623d5e7489751812d628e29d0e22075c94a2e99681ecf70be3977ad
    lastState: {}
    name: git-sync
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://55c2100d7a11b2e3c9bce8daacabd5b2b75257cb0fe189857b70e82e95645b43
        exitCode: 0
        finishedAt: "2021-02-23T06:27:28Z"
        reason: Completed
        startedAt: "2021-02-23T06:27:25Z"
```

deployment.yaml sectio:
```
      initContainers:
        - image: {{ include "image.gitsync" . }}
          name: git-sync
          volumeMounts:
            - name: model-repository
              mountPath: {{ .Values.gitsync.folderpath }}
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 500Mi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: GIT_SYNC_REPO
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}.models
                  key: repo
            - name: GIT_SYNC_ROOT
              value: {{ .Values.gitsync.folderpath }}
            - name: GIT_SYNC_DEST
              value: repository
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.branch | required "A valid branch or tag for models called branch repo is required" }}
            - name: GIT_SYNC_REV
              value: {{ .Values.revision | required "A valid branch or tag for models called revision repo is required" }}
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
```

Below log states failed, even the init conatiner exists with status 0 and continues with regular pod to start, what shall not happen.
Instead the init container shall return code 128 and fail with init and so fail the whole pod as expected.
kubectl logs XXXXXXX-5f9c474675-mg5kc -c git-sync -nnonprod
```
INFO: detected pid 1, running init handler
I0223 06:27:25.213737      11 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=11
I0223 06:27:25.214058      11 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="https://anyuser:SECRET@dev.azure.com/XXXXX/XXXXX/_git/XXXXXX" "path"="/tmp/git"
E0223 06:27:28.438939      11 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git rev-parse 65f08a7): exit status 128: { stdout: \"65f08a7\\n\", stderr: \"fatal: ambiguous argument '65f08a7': unknown revision or path not in the working tree.\\nUse '--' to separate paths from revisions, like this:\\n'git \u003ccommand\u003e [\u003crevision\u003e...] -- [\u003cfile\u003e...]'\\n\" }"  "failCount"=0
```

I assume thta even the clone of branch failed and it still tries to change to revision GIT_SYNC_REV afterwards based on an invalid failed local cloned repo. Please check if the fail of GIT_SYNC_REV change might not be exported as return code . 
Or is there anything why i need to do different to use the container to get failed in that case too?

Maybe GIT_SYNC_DEPTH 1 is pruning history and so for unusable together with GIT_SYNC_REV which might be prunned?
