### ISSUE TITLE
RPC failed; curl 56 GnuTLS recv error 

### ISSUE THREAD

**Issue by cforce** [kubernetes/git-sync#340]
stdout: \"\", stderr: \"Cloning into '/tmp/git'...\\nerror: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.\\nfatal: the remote end hung up unexpectedly\\nfatal: early EOF\\nfatal: index-pack failed\\n\

According to https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls
i would need to git config --global http.postBuffer 1048576000 or
"Rebuilding git with openssl instead of gnutls"

**Comment by thockin** [comment]
Hi, I have proposed #341 as a way to pass arbitrary args.

**Comment by cforce** [comment]
What is necessary for me to use it in an k8 init container? Does it then look like this?
```
      initContainers:
        - image: {{ include "image.gitsync" . }}
          name: git-sync
          args: ["--git-config", "http.postBuffer:1048576000"]
          env:
            - name: GIT_SYNC_REPO
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}.models
                  key: repo
            - name: GIT_SYNC_ROOT
              value: {{ .Values.gitsync.folderpath }}
            - name: GIT_SYNC_DEST
              value: repository
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.models.branch | required "A valid branch or tag for models called models.branch repo is required" }}
            - name: GIT_SYNC_REV
              value: {{ .Values.models.revision | required "A valid branch or tag for mis models called models.revision repo is required" }}
              # we need to pull complete history, because pod restart will clone from scratch and recent head and still need to find GIT_SYNC_REV back in history
            - name: GIT_SYNC_DEPTH 
              value: "0"
            - name: GIT_SYNC_ONE_TIME
              value: "true"

```
