### ISSUE TITLE
Error when cloning from gitlab

### ISSUE THREAD

**Issue by rjribeiro** [kubernetes/git-sync#355]
i have this error when i try clone a repo on gitlab 

`E0317 20:42:35.838059       1 main.go:186] error syncing repo: error running command: exit status 128: "fatal: could not read Username for 'https://github.com': No such device or address\n"
`
the username and passwords are corrects.

here the code

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: airflow-k8s
  name: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      restartPolicy: Always
      containers:
      - name: git-sync
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        image: k8s.gcr.io/git-sync:v3.1.5
        imagePullPolicy: IfNotPresent
        env:
          - name: GIT_SYNC_REPO
            value: "https://gitlab.com/xxxxx.git"
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_ROOT
            value: "/git"
          - name: GIT_SYNC_DEST
            value: "sync"
          - name: GIT_SYNC_USERNAME
            value: "xxxxx"
          - name: GIT_SYNC_PASSWORD
            value: "xxxxx"
          - name: GIT_SYNC_WAIT
            value: "10"
          - name: GIT_SYNC_ONE_TIME
            value: "False"
          - name: GIT_SYNC_PERMISSIONS
            value: "777"
          - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
            value: "10"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_KNOWN_HOSTS
            value: "false"
        volumeMounts:
          - name: dags
            mountPath: /git
      volumes:
          - name: persistent-storage-data-logs
            hostPath:
              path: /airflow-k8s-data
              type: DirectoryOrCreate
          - name: dags
            persistentVolumeClaim:
              claimName: pv-claim-dags
```
