### ISSUE TITLE
Error on git-sync running as a CronJon

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubernetes/git-sync#439]
Hi,
I'm using git-sync `v3.3.4` in a CrobJob as an initContainer. It's a definition:
```
- name: clone-results-repo
  image: "{{ .Values.init.cloneRepo.image.repository }}:{{ .Values.init.cloneRepo.image.tag }}"
  imagePullPolicy: {{ .Values.init.cloneRepo.image.pullPolicy }}
  volumeMounts:
    - name: persistent-storage
      mountPath: /git
  env:
  - name: GIT_SYNC_REPO
    value: {{ .Values.git.url }}
  - name: GIT_SYNC_ONE_TIME
    value: "true"
  - name: GIT_SYNC_BRANCH
    value: my_awesome_branch
  - name: GIT_SYNC_DEPTH
    value: "1"
  - name: GIT_SYNC_USERNAME
    valueFrom:
      secretKeyRef:
        name: {{ include "my-awesome-app.fullname" . }}-git-credentials
        key: GIT_PULL_USERNAME
  - name: GIT_SYNC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "my-awesome-app.fullname" . }}-git-credentials
        key: GIT_PULL_PASSWORD
  - name: GIT_SYNC_ROOT
    value: /git
  - name: GIT_SYNC_TIMEOUT
    value: "99999"
```
There is another container which also mounts `persistent-storage` volume and consumes the data from the cloned repo. The issue is that after few succeeded executions I have always the same error:
```
INFO: detected pid 1, running init handler
I0809 06:29:23.648815      11 main.go:507] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync"]
I0809 06:29:24.077876      11 main.go:1003] "level"=0 "msg"="update required" "rev"="HEAD" "local"="1172cc4eeed3a3dd6d5e8fb65f3c15134adf9f32" "remote"="bfa07ea5354c25fa7e267dbcb6bbb305f2bd315f"
I0809 06:29:24.077969      11 main.go:690] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="bfa07ea5354c25fa7e267dbcb6bbb305f2bd315f"
E0809 06:29:24.702409      11 main.go:172] "msg"="too many failures, aborting" "error"="Run(git gc --prune=all): exit status 128: { stdout: "", stderr: "fatal: gc is already running on machine 'my-awesome-app-1628460000-pr7v8' pid 49 (use --force if not)\n" }" "failCount"=0
```
and pod `my-awesome-app-1628460000-pr7v8` does not exist anymore.
Repository has c.a. 7GB of data (if it matters).

**Comment by thockin** [comment]
It looks like `git gc` was running and terminated early (e.g. your pod
died) and since you user persistent storage, it's "corrupt".  I am trying
to reproduce this so I can figure out what to do, but not having any luck.
You can't send me a tarfile of your repo in this state, can you?

**Comment by michal-jagiello-tmpl** [comment]
@thockin no, unfortunately not :| is that `git gc` runs asyncronously? Can that process be somehow interrupted?

**Comment by thockin** [comment]
I'm not really a git expert, so that's what I want to figure out :(

**Comment by thockin** [comment]
I mean, I could just add a `--force` and cross my fingers.  Or I could add a `--skip-gc` flag for cases that are not going to be long-lived.  But that seems likely to end in repo bloat.  If you never ever GC it becuase you never have time, then what?

**Comment by thockin** [comment]
You could try `--git-config=gc.autoDetach:false` ?  That could become the default if it works...

Or we could catch this specific case ("already running") and not treat it as fatal.

Without a repro, it's scary.

**Comment by michal-jagiello-tmpl** [comment]
I've run that cron with
```
env:
....
  - name: GIT_SYNC_GIT_CONFIG
    value: "gc.autoDetach:false"
```
but there is in [doc](https://git-scm.com/docs/git-gc#Documentation/git-gc.txt-gcautoDetach):
```
gc.autoDetach
    Make git gc --auto return immediately and run in background if the system supports it. Default is true.
```
I see that you call `git gc prune --all` [here](https://github.com/kubernetes/git-sync/blob/259f7d80007b0f2342756b359c3a7f3a80e99348/cmd/git-sync/main.go#L712).
Maybe the solution could be to add `--disable-git-gc` flag if user is absolutely sure what they doing and I could care myself about that. I'll run `git gc` by myself once a day and not every few hours?
