### ISSUE TITLE
Can't work when use secretRef on Kubernetes.

### ISSUE THREAD

**Issue by jingcheng88** [kubernetes/git-sync#443]
```
apiVersion: v1
kind: Secret
metadata:
name: git-credentials
data:
    GIT_SYNC_USERNAME: <base64_encoded_git_username>
    GIT_SYNC_PASSWORD: <base64_encoded_git_password>
```
```
- name: GIT_SYNC_USERNAME
  valueFrom:
    secretKeyRef:
       name: {{ .Values.dags.gitSync.credentialsSecret | quote }}
       key: GIT_SYNC_USERNAME
- name: GIT_SYNC_PASSWORD
  valueFrom:
    secretKeyRef:
       name: {{ .Values.dags.gitSync.credentialsSecret | quote }}
       key: GIT_SYNC_PASSWORD
```

git-sync can not work with this kind of env.
```
Cloning into '/dags'...\nfatal: could not read Username for 'https://xxxxxx': No such device or address
```

**Comment by thockin** [comment]
Can you please paste more complete logs?

Can you confirm that the values you expect to be in those env vars are actually present by changing the command and args to something like `sleep` and `10000` respectively, then `kubectl exec` and verify?

Make sure there's no errant newline in your secret data, too.

**Comment by jingcheng88** [comment]
> Can you please paste more complete logs?
> 
> Can you confirm that the values you expect to be in those env vars are actually present by changing the command and args to something like `sleep` and `10000` respectively, then `kubectl exec` and verify?
> 
> Make sure there's no errant newline in your secret data, too.

I confirm these env by using `kubectl describe pod` and `kubectl exec`.

It worked when i set as following. But it could not recognize `GIT_SYNC_USERNAME`from env when i use secretKeyRef。
```
env: 
    - name: "GIT_SYNC_USERNAME"
      value: "xxxxx"
    - name: "GIT_SYNC_PASSWORD"
      value: "xxxxxx"
```

**Comment by thockin** [comment]
This doesn't make sense - either the car is set or it isn't - git-sync
doesn't know HOW.

Can you paste full logs?

**Comment by minhthong582000** [comment]
yes, this happened to me when i'm using https://github.com/apache/airflow/tree/main/chart.

extra-secret.yaml

```
apiVersion: v1
data:
  GIT_SYNC_PASSWORD: xxxxx
  GIT_SYNC_USERNAME: xxxxx
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow-cluster
type: Opaque
```

scheduler-deployment.yaml:

```
-  name: git-sync
    image: k8s.gcr.io/git-sync/git-sync:v3.3.4
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 65533
    env:
      - name: GIT_SYNC_USERNAME
        valueFrom:
          secretKeyRef:
            name: "git-credentials"
            key: GIT_SYNC_USERNAME
      - name: GIT_SYNC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "git-credentials"
            key: GIT_SYNC_PASSWORD
      - name: GIT_SYNC_REV
        value: "HEAD"
      - name: GIT_SYNC_BRANCH
        value: "main"
      - name: GIT_SYNC_REPO
        value: "https://gitlab.com/<my-rep>"
      - name: GIT_SYNC_DEPTH
        value: "1"
      - name: GIT_SYNC_ROOT
        value: "/git"
      - name: GIT_SYNC_DEST
        value: "repo"
      - name: GIT_SYNC_ADD_USER
        value: "true"
      - name: GIT_SYNC_WAIT
        value: "60"
      - name: GIT_SYNC_MAX_SYNC_FAILURES
        value: "10"
    resources: 
        {}
    volumeMounts:
    - name: dags
      mountPath: /git
```

Logs:

```
INFO: detected pid 1, running init handler
I1002 06:36:59.816160      11 main.go:507] "level"=0 "msg"="starting up" "pid"=11 "args"=["/git-sync"]
I1002 06:36:59.816261      11 main.go:860] "level"=0 "msg"="cloning repo" "origin"="https://gitlab.com/<my-repo>.git" "path"="/git"
E1002 06:37:00.049198      11 main.go:172] "msg"="unexpected error syncing repo, will retry" "error"="Run(git clone --no-checkout -b main --depth 1 https://gitlab.com/<my-repo>.git /git): exit status 128: { stdout: "", stderr: "Cloning into '/git'...\nfatal: could not read Username for 'https://gitlab.com/<my-repo>': No such device or address\n" }"
I1002 06:37:00.049237      11 main.go:538] "level"=0 "msg"="waiting before retrying" "waitTime"=60000000000
```

**Comment by minhthong582000** [comment]
I know where my problem come from. There is a "\n" behind my base64 username and password. Remove it and it works. Thanks @thockin !

**Comment by thockin** [comment]
That's what I expected - it's, sadly, a common error.

**Comment by huzerun0306** [comment]
@thockin  Hello, I have the same problem, it seems to be a problem of \n, but I am very sure that my secret is not added with \n, this might it be the default behavior?
this is my yaml file:
```
        args:
          - -repo=https://xxxx.git
          - -wait=60
          - -dest=/data/repo/
        env:
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: kubediff-secret
              key: username
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kubediff-secret
              key: password
```
and secret.yaml (password is hidden)
```
apiVersion: v1
kind: Secret
metadata:
  name: kubediff-secret
type: Opaque
data:
  username: emVydW5odQo=
  password: xxxxxxxxxxxxxxx
```
We can see that this is 'zerunhu' encrypted by base64 and not add \n
![image](https://user-images.githubusercontent.com/44351924/162761457-6db19c8e-7ef9-43f8-9481-d0eeadd20f06.png)

Then I started debugging. I deliberately wrote the parameters of args wrong, made git-sync report an error, and output the log. 

I modified the containers.args of the yaml file, adding a line:
```
args:
  - usernamee=yyy

```

The log will display the default values of username and password. I saw that the username here is added with a \n

![image](https://user-images.githubusercontent.com/44351924/162762211-81b86e2e-6483-487e-adfe-97077291b2a6.png)

I continued to debug, and exec entered the pod. Then I checked my environment variables and found that there was no problem. Then I tried to execute the command git clone and found that he needed to enter a password, and the environment variables did not take effect.
![image](https://user-images.githubusercontent.com/44351924/162762848-a8951dad-8145-4f3e-96c3-13489e53a0d5.png)

It seems that git-sync adds \n to my secret by default? It can be seen that \n is not added to the secret data, but it is added when git-sync is executed. It has been a day since I solved this problem. I really hope the team can give me some help.
thank you very much！

**Comment by thockin** [comment]
Which version of git-sync?  Try this:

```
$ GIT_SYNC_PASSWORD=foo bin/linux_amd64/git-sync -badarg 2>&1 | grep foo
    	the password to use for git auth (prefer --password-file or this env var) (default "foo")
```

So it's clear that git-sync itself is not adding a newline.

Using `env` is suspect, too.

```
$ export X="foo
> "
$ env | grep X=
X=foo
$ echo before${X}after
beforefoo after
$ echo before"$X"after
beforefoo
after
```

**Comment by Asgoret** [comment]
@thockin same problem here. With Apache Airflow helm chart. Last stable version of chart if 1.7.0 and it's used git-sync v3.4.0. I tried moved to v3.6.2, but got errors from airflow db migration

**Comment by thockin** [comment]
Which "same problem"?  All of these appear to be user error (including a
newline in the secret).

**Comment by Asgoret** [comment]
`'...\nfatal: could not read Username for 'https://xxxxxx': No such device
or address`

I check twice how values where encrypted, but there is no new line.
Tomorrow will create demo stand and get

ср, 28 дек. 2022 г., 23:14 Tim Hockin ***@***.***>:

> Which "same problem"? All of these appear to be user error (including a
> newline in the secret).
>

**Comment by Asgoret** [comment]
@zerunhu did u find solution or workaround? I have similar situation. In secret or env inside pod there is not `\n`, but git-sync add `\n` in default value.

**Comment by Asgoret** [comment]
Username in env:
![image](https://user-images.githubusercontent.com/30697011/209939715-c2b9ca1d-269e-4318-9653-f4cb3b030269.png)
Username in git-sync:
![image](https://user-images.githubusercontent.com/30697011/209939778-791f9459-d193-47c4-a067-0a843678d61e.png)

**Comment by Asgoret** [comment]
@thockin 
Hope, I found the root of the problem.
If u write yaml file like this all works:
```
    env:
    - name: GIT_SYNC_USERNAME
      value: "<VALUE>"
    - name: GIT_SYNC_PASSWORD
      value: "<VALUE>"
````

If u use secretKeyRef somewhere `\n` added u got error `Cloning into '/dags'...\nfatal: could not read Username for 'https://xxxxxx': No such device or address` because git-sync ignored username and password default:
```
    env:
    - name: GIT_SYNC_USERNAME
      valueFrom:
        secretKeyRef:
          key: GIT_SYNC_USERNAME
          name: gitsync-apache-airflow-bot
    - name: GIT_SYNC_PASSWORD
      valueFrom:
        secretKeyRef:
          key: GIT_SYNC_PASSWORD
          name: gitsync-apache-airflow-bot
```
