### ISSUE TITLE
subPath volumeMount issue

### ISSUE THREAD

**Issue by naude-r** [kubernetes/git-sync#519]
good day,

we are using the subPath option in volumeMount to mount a specific sub=directory from git.

if the repo is updated the symlink is removed and re-created to the latest revision. unfortunately k8s does not re-mount the subPath leading to empty resources.

as an example:
```
image: git-sync
args
  - "-repo=https://repo/resources.git"
  - "-branch=dev"
  - "-root=/data"
  - "-dest=resources"
volumeMounts:
- name: template-volume
  mountPath: /data
image: app
volumeMounts:
 - name: template-volume
    mountPath: /app/resources
    subPath: resources
```

after the checkout we have in /data
resources -> a5128f5116d4b3bbf310c01c61efbbe88231ab79
a5128f5116d4b3bbf310c01c61efbbe88231ab79

if we now update the repo, the resouces symlink will be replaced and the app mount, /app/resources, will be empty.
81aa6ea2af9cd4dedcaf022d3ddfbca484ca610a
resources -> 81aa6ea2af9cd4dedcaf022d3ddfbca484ca610a

not using the subPath results in /app/resources/resources/. not a big deal, but if it can be resolved it would be great.
