### ISSUE TITLE
Multiple zombie processes after a couple of days running

### ISSUE THREAD

**Issue by aledbf** [kubernetes/git-sync#55]
Today I found a pod that is running since `Mon, 27 Mar 2017 19:20:53 -0300` has 1745 zombie child processes. The deployment is configured with this env variables:
```yaml
        - name: GIT_SYNC_REPO
          value: http://xxxxxxxxx.git
        - name: GIT_SYNC_DEST
          value: data
        - name: GIT_SYNC_WAIT
          value: "300"
        - name: GIT_SYNC_USERNAME
          value: xxxxxxxxx
        - name: GIT_SYNC_PASSWORD
          value: xxxxxxxxx
        - name: GIT_SYNC_MAX_SYNC_FAILURES
          value: "999999"
        - name: GIT_SYNC_PERMISSIONS
          value: "755"
        - name: GIT_SYNC_ROOT
          value: /git
```

**image:** gcr.io/google_containers/git-sync-amd64:v2.0.4

```console
11349 ?        Sl     0:00  \_ /usr/bin/containerd-shim 014cc79294083c25fe69e13acb30cb35977585b086806466ff269c3841116225 /var/run/docker/libcontainerd/014cc79294083c25fe69e13acb30cb35977585b086806466ff269c3841116225 docker-runc
11366 ?        Ssl    0:08  |   \_ /git-sync
11416 ?        Z      0:00  |       \_ [git-credential-] <defunct>
10949 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
30826 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
21644 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 8790 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
27684 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
15016 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 1260 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
20780 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 7507 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
26587 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
13586 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
32364 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
19541 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 6487 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
25368 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
12562 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
30987 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
18188 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 4824 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
24131 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
11333 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
30182 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
17435 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 3827 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
22832 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
10001 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
28827 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
16080 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 2909 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
22296 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
 9650 ?        Z      0:00  |       \_ [git-remote-http] <defunct>
.......
```
