### ISSUE TITLE
How to notify another container in the same pod when a symlink is flipped?

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/git-sync#6]
Hi, thanks for sharing this 👍 

Do you have any idea about how to notify another container to reload files immediately after git-sync successfully ran?

My use-case is that
(1) git-sync periodically checks my git repo containing PHP/Ruby/etc web app sources
(2) though my app doesn't support hot-reloading on symlink flip (which git-sync does for atomicity of updates),
(3) I'd like my app to reload/restart once git-sync updated sources

I had thought of sending signals from git-sync to notify my app for reloading.
Kubernetes doesn't currently support sending signals between containers/pods https://github.com/kubernetes/kubernetes/issues/24957

**Comment by thockin** [comment]
You can inotify on the symlink - you're right that signalling across containers is not yet supported.

**Comment by jeff-knurek** [comment]
sorry for the naive questions here, but  how is this suppose to work? 
The demo example with `hugo` is pretty close to my use cases, and it seems like the hugo container in that example runs with `server --watch /sync-dir`, but here you're talking about using `inotify`. 
Basically, I want to be able to trigger a bash command once git-sync updated sources, but I don't see a clear way of doing that...

**Comment by thockin** [comment]
I just realized the widely used fsnotify lib doesn't handle symlinks well.  Bah.

Blatantly ripped off from older golang.org/x/exp/inotify



```
package main

import (
	"errors"
	"log"
	"os"
	"path"
	"strings"
	"syscall"
	"unsafe"
)

func main() {
	Notify("/tmp/git/link", func(ev *Event) { log.Println("event:", ev.Name) })
}

// Notify calls fn whenever link is moved to (as per inotify).  This will not
// return unless there is an error.
func Notify(link string, fn func(*Event)) error {
	n, err := newNotifier()
	if err != nil {
		return err
	}
	dir, file := path.Split(link)
	err = n.watch(dir)
	if err != nil {
		return err
	}
	for {
		select {
		case ev := <-n.Event:
			if ev.Name == file {
				fn(ev)
			}
		case err := <-n.Error:
			return err
		}
	}
	// Should never get here.
	return nil
}

type Event struct {
	Mask   uint32 // Mask of events
	Cookie uint32 // Unique cookie associating related events (for rename(2))
	Name   string // File name (optional)
}

type notifier struct {
	fd    int         // File descriptor (as returned by the inotify_init() syscall)
	wd    uint32      // Watch descriptor (as returned by the inotify_add_watch() syscall)
	Error chan error  // Errors are sent on this channel
	Event chan *Event // Events are returned on this channel
}

// newNotifier creates and returns a new inotify instance using inotify_init(2)
func newNotifier() (*notifier, error) {
	fd, errno := syscall.InotifyInit()
	if fd == -1 {
		return nil, os.NewSyscallError("inotify_init", errno)
	}
	notifier := &notifier{
		fd:    fd,
		Event: make(chan *Event),
		Error: make(chan error),
	}

	go notifier.readEvents()
	return notifier, nil
}

// watch watches dir for IN_MOVED_TO events.
func (notifier *notifier) watch(dir string) error {
	wd, err := syscall.InotifyAddWatch(notifier.fd, dir, IN_MOVED_TO|IN_DONT_FOLLOW|IN_ONLYDIR)
	if err != nil {
		return &os.PathError{
			Op:   "inotify_add_watch",
			Path: dir,
			Err:  err,
		}
	}

	notifier.wd = uint32(wd)
	return nil
}

// readEvents reads from the inotify file descriptor, converts the
// received events into Event objects and sends them via the Event channel
func (notifier *notifier) readEvents() {
	var buf [syscall.SizeofInotifyEvent * 4096]byte

	for {
		n, err := syscall.Read(notifier.fd, buf[:])

		// If EOF...
		if n == 0 {
			// The syscall.Close can be slow.  Close
			// notifier.Event first.
			close(notifier.Event)
			err := syscall.Close(notifier.fd)
			if err != nil {
				notifier.Error <- os.NewSyscallError("close", err)
			}
			close(notifier.Error)
			return
		}
		if n < 0 {
			notifier.Error <- os.NewSyscallError("read", err)
			continue
		}
		if n < syscall.SizeofInotifyEvent {
			notifier.Error <- errors.New("inotify: short read in readEvents()")
			continue
		}

		var offset uint32 = 0
		// We don't know how many events we just read into the buffer
		// While the offset points to at least one whole event...
		for offset <= uint32(n-syscall.SizeofInotifyEvent) {
			// Point "raw" to the event in the buffer
			raw := (*syscall.InotifyEvent)(unsafe.Pointer(&buf[offset]))
			event := new(Event)
			event.Mask = uint32(raw.Mask)
			event.Cookie = uint32(raw.Cookie)
			nameLen := uint32(raw.Len)
			if nameLen > 0 {
				// Point "bytes" at the first byte of the filename
				bytes := (*[syscall.PathMax]byte)(unsafe.Pointer(&buf[offset+syscall.SizeofInotifyEvent]))
				// The filename is padded with NUL bytes. TrimRight() gets rid of those.
				event.Name = strings.TrimRight(string(bytes[0:nameLen]), "\000")
			}
			// Send the event on the events channel
			notifier.Event <- event
			// Move to the next event in the buffer
			offset += syscall.SizeofInotifyEvent + nameLen
		}
	}
}

const (
	// Options for AddWatch
	IN_DONT_FOLLOW uint32 = syscall.IN_DONT_FOLLOW
	IN_ONLYDIR     uint32 = syscall.IN_ONLYDIR

	// Events
	IN_MOVED_TO uint32 = syscall.IN_MOVED_TO
)
```

**Comment by shubhamc183** [comment]
@thockin can you elaborate on how to `inotify` the symlink?

I am mounting the `data`(symlink) via `subPath` but the /etc/data is giving  `sh: getcwd: No such file or directory` error.
```
........................................
      containers:
        - name: alpine
          image: alpine:3.13.5
          volumeMounts:
          - name: gitvolume
            mountPath: /etc/data
            subPath: data
          stdin: true
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.0
          volumeMounts:
          - name: gitvolume
            mountPath: "/workspace"
          - name: ssh-key
            mountPath: /etc/git-secret/
            readOnly: true
          env:
          - name: GIT_SYNC_ROOT
            value: "/workspace"
          - name: GIT_SYNC_DEST
            value: "data"
          - name: GIT_SYNC_WAIT
            value: "10"
........................................
      - name: gitvolume
        emptyDir: {}
```

If I make the above git-sync as `initContainer` then it works fine.

Content is not synced as docker volume symlink is refreshed. (**I'm assuming**).
![image](https://user-images.githubusercontent.com/15362871/117149400-d13c6400-add4-11eb-8082-d54b02b45455.png)

Without `subPath` the contents can be seen at `/etc/data/*`
![image](https://user-images.githubusercontent.com/15362871/117150060-6fc8c500-add5-11eb-8b2a-cd4b4d75b924.png)

So, is it possible to mount under `/etc/data/` instead of `/etc/data/data` with git-sync as a sidecar where `/etc/` have other directories as well?
