### ISSUE TITLE
Cloning a Git repo into the current directory

### ISSUE THREAD

**Issue by buraksekili** [kubernetes/git-sync#636]
Hi,

Is it possible to clone the git repository into the root directory without creating an additional folder? 
For example, `git clone <address> .` clones git repository to the current folder. Is it doable with git-sync?

- The structure of my git repository is as follows:
```
.
├── folder1
│   ├── file.json
│   └── another-file.txt
├── folder2 (empty folder)
    └── .gitkeep
└── folder3
    └──file.json
```

- I am running `git-sync` in `initContainers`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  initContainers:
        - name: "git-sync"
          image: k8s.gcr.io/git-sync/git-sync:v3.6.1
          workingDir: /mnt/my-app
          volumeMounts:
            - name: myapp-scratch
              mountPath: /mnt/my-app
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
          securityContext:
            runAsUser: 65533 # git-sync user
          env:
            - name: GIT_SYNC_REPO
              value: "<repo>"
            - name: GIT_SYNC_BRANCH
              value:  "master"
            - name: GIT_SYNC_ROOT
              value: "/mnt/my-app"
            - name: GIT_SYNC_PERMISSIONS
              value: "0777"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_SSH
              value: "true"
  volumes:
        - name: myapp-scratch
          emptyDir: {}
```

I have an `emptyDir` volume mounted at `/mnt/my-app` where it contains some configuration files for my container. Before running my container, I would like to fetch the latest configurations from the git repository and add these configurations to `/mnt/my-app` directory; so that my container can access these configurations via `/mnt/my-app/folder1`, `/mnt/my-app/folder2` and `/mnt/my-app/folder3`. 

However, `git-sync` clones the git repo under `/mnt/my-app/rev<hash>`, as follows:
```bash
$ ls /mnt/my-app/
rev-<hash>  my-app.git

$ ls /mnt/my-app/rev-<hash>
folder1  folder2  folder3
```

Is it possible to put all contents into the current volume's path? For instance, `/mnt/my-app/folder1` instead of `/mnt/my-app/rev/folder1`?

Thanks in advance!
