### ISSUE TITLE
Question: Works with Bitbucket repos?

### ISSUE THREAD

**Issue by App-247** [kubernetes/git-sync#70]
I tried unsuccessfully to clone a private repo on Bitbucket. With repositories in github works wonderfully. This works for Bitbucket repos? Thanks.

**Comment by stp-ip** [comment]
This is basically using plain git over http or ssh... So there shouldn't be any difference to the hosted git repository. What method did you use and what was the error you encountered?

**Comment by gorozcoh** [comment]
Container git-syn in my pod:
```
spec:
      containers:
        - name: git-sync
          image: gcr.io/google_containers/git-sync:v2.0.4
          imagePullPolicy: Always
          volumeMounts:
          - name: git-sync
            mountPath: /git
          env:
          - name: GIT_SYNC_REPO
            value: https://bitbucket.org/app247/comercio-addons
          - name: GIT_SYNC_DEST
            value: git
          - name: GIT_SYNC_USERNAME
            value: my-username
          - name: GIT_SYNC_PASSWORD
            value: my-password
```
Volume git-sync is emptyDir: {}
In describe pod:

```
 <invalid>     <invalid>       1       kubelet, gke-cluster-1-default-pool-69a7e6ee-hrrd       spec.containers{git-sync}       Normal          Created         Created container with id 413962123e3f46243532d32d0ddbd007a8012bf68b61111d3d6bb596dd553a61
  <invalid>     <invalid>       1       kubelet, gke-cluster-1-default-pool-69a7e6ee-hrrd       spec.containers{git-sync}       Normal          Started         Started container with id 413962123e3f46243532d32d0ddbd007a8012bf68b61111d3d6bb596dd553a61
  <invalid>     <invalid>       2       kubelet, gke-cluster-1-default-pool-69a7e6ee-hrrd                                       Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "git-sync" with CrashLoopBackOff: "Back-off 10s restarting failed container=git-sync pod=odoo-10-comercio-4113950861-k7sq2_app-247-1(0964ce24-9d4d-11e7-8712-42010af002d5)"

```
Thanks.
