### ISSUE TITLE
Using git-sync in kubernetes with SSH

### ISSUE THREAD

**Issue by austin-stytch** [kubernetes/git-sync#706]
Hi! Similar to #702 I'm not sure how to get passed `Host key verification failed`

I have a kubernetes initContainer like:

```
initContainers:
  - image: registry.k8s.io/git-sync/git-sync:v3.6.5
    name: protobuf-repository-setup
    args:
      - "-repo=ssh://git@github.com/stytchauth/protobuf.git"
      - "-rev=HEAD"
      - "-branch=main"
      - "-depth=1"
      - "-max-sync-failures=2"
      - "-wait=10"
      - "-one-time=true"
      - "-root=/backend/protobuf"
      - "-dest=/backend/protobuf-dest"
      - "-ssh=true"
      - "-add-user"
      - "-v=99"
    volumeMounts:
      - name: git-secret
        mountPath: /etc/git-secret
        readOnly: true
      - name: protobuf
        mountPath: "/backend"
        readOnly: false
```

with 

```
      volumes:
        - emptyDir: {}
          name: protobuf
        - name: git-secret
          secret:
            defaultMode: 256
            secretName: git-creds
```

and

```
        volumeMounts:
        - mountPath: /etc/git-secret
          name: git-secret
          readOnly: true
```

but get messages like

```
E0403 20:45:00.941734      12 main.go:551] "msg"="error syncing repo, will retry" "error"="Run(git clone -v --no-checkout -b main --depth 1 ssh://git@github.com/stytchauth/protobuf.git /backend/protobuf): exit status 128: { stdout: "", stderr: "Cloning into '/backend/protobuf'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." }" "failCount"=2 "waitTime"=10000000000
```

I've tried:

```
      - "-repo=ssh://git@github.com/stytchauth/protobuf.git"
```

and

```
      - "-repo=git@github.com:stytchauth/protobuf.git"
```

to no avail. 

From my laptops, I'm able to run similar commands with the same key

```
% git clone -v --no-checkout -b main --depth 1 ssh://git@github.com/stytchauth/protobuf.git
Cloning into 'protobuf'...
```

Do you have any advice on how to debug this ssh connection? Thank you!
