### ISSUE TITLE
docker build -t myrepo/hugo hugo/ => Failed to recurse into submodule path 'sublime-hugo-theme'

### ISSUE THREAD

**Issue by alexryan** [kubernetes/git-sync#74]
```
 😈   >docker build -t myrepo/hugo hugo/
Sending build context to Docker daemon  5.632kB
Step 1/13 : FROM golang
...
Submodule path 'would-have-been-cool-in-the-80s': checked out '7933ce7d6aad4ecf38edc217340c1004dd8f01fb'
Failed to recurse into submodule path 'sublime-hugo-theme'
The command '/bin/sh -c git clone --recursive https://github.com/spf13/hugoThemes.git /themes' returned a non-zero code: 1
```

**Comment by thockin** [comment]
I'm sorry, what about this is this a git-sync issue?

**Comment by alexryan** [comment]
Neither of the demos for git-sync work.
The docker example does not work. Issue #72 
The kubernetes example also does not work.
This failed command is from the instructions for [git-blog-demo](https://github.com/kubernetes/git-sync/tree/master/demo)
Kindly suggest how to get a git-sync actually running on kubernetes.
Thanks.

**Comment by thockin** [comment]
Ahh, sorry.  Yes, it's been on teh TODO list for a long time to fix examples.

```
      volumes:
        - name: content
          emptyDir: {}
```

and

```
      containers:
        - name: git-sync
          image: gcr.io/google_containers/git-sync-amd64:v2.0.4
          args:
            - -repo=https://github.com/you/your-repo
            - -branch=master
            - -depth=1
            - -wait=60
            - -dest=html
            - -max-sync-failures=1000000000
            - -v=2
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 16Mi
          volumeMounts:
            - name: content
              mountPath: /git
```
