### ISSUE TITLE
sparse checkout not working

### ISSUE THREAD

**Issue by harshitasaxena05** [kubernetes/git-sync#776]
Hi, I'm trying to use git-sync with sparse checkout feature

I'm having https://dummy.git repo containing /output dir having files - a.txt, b.txt.

I want to download a.txt only.

Below are the env and volume mount I have set -

```
       env:
         - name: GIT_SYNC_REPO
           value:  https://dummy.git
         - name: GIT_SYNC_DEST
           value: git-sync
         - name: GIT_SYNC_USERNAME
           value: user
         - name: GIT_SYNC_PASSWORD
           value: pwd
         - name: GITSYNC_SPARSE_CHECKOUT_FILE
           value: "output/a.txt"

      volumeMounts:
        - name: content-from-git
          mountPath: /tmp/git
```

**image version:** v3.6.6

**Below is the error output -** 

"msg"="too many failures, aborting" "error"="open /output/a.txt: no such file or directory" "failCount"=1

If I don't set this env GITSYNC_SPARSE_CHECKOUT_FILE, it's working by cloning entire repo inside /tmp/git/git-sync/
 
 Can anyone help in resolving this issue? Thanks.
