### ISSUE TITLE
[Question] Setting up git-sync to get submodules on helm-chart

### ISSUE THREAD

**Issue by ImmortalLotus** [kubernetes/git-sync#823]
I am using airflow's helm chart, and I have this

```
gitSync:
    enabled: true
    repo: url_to_repo
    branch: main
    subPath: dags
```

what do I need to add in order to sync submodules?
