### ISSUE TITLE
GITSYNC_SSH_KNOWN_HOSTS=false doesn't work?

### ISSUE THREAD

**Issue by abh** [kubernetes/git-sync#824]
I set `GITSYNC_SSH_KNOWN_HOSTS=false` in my environment, but git-sync is still failing with a host verification error:

```
 HEAD HEAD^{}): exit status 128: { stdout: \"\", stderr: \"Host key verification failed.\\r\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\" }","failCount":1}
```

```
  - env:
    - name: GITSYNC_REPO
      value: git@gitea-ssh.gitosis.svc.cluster.local:user/repo.git
    - name: GITSYNC_SSH_KNOWN_HOSTS
      value: "false"
    - name: GITSYNC_LINK
      value: a
    - name: GITSYNC_ROOT
      value: /git/static
    - name: GITSYNC_MAX_FAILURES
      value: "-1"
    - name: GITSYNC_PERIOD
      value: 2m
    - name: GITSYNC_HTTP_BIND
      value: :8071
    image: registry.k8s.io/git-sync/git-sync:v4.0.0
```

Separately but maybe related: I do have a `/etc/git-secret/known_hosts` file and I tested it with a regular ssh client, but something else seems to be wrong that git-sync isn't reading that file (or using the keys from it correctly).
