### ISSUE TITLE
git-sync with nfs-volume 

### ISSUE THREAD

**Issue by ZackovichZ** [kubernetes/git-sync#839]
I'm trying to deploy git-sync using nfs-share, but for some reason when using this type of volume - the container crashes on startup

**manifest:** 

```
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: dev-test
   namespace: test
 spec:
   template:
     metadata:
     spec:
       containers:
       - env:
         - name: GITSYNC_REPO
           value: <any repo>
         - name: GITSYNC_REF
           value: master
         - name: GITSYNC_ROOT
           value: /git
         - name: GITSYNC_LINK
           value: www
         - name: GITSYNC_PERIOD
           value: 2s
         - name: GIT_DISCOVERY_ACROSS_FILESYSTEM
           value: "1"
         envFrom:
         - secretRef:
             name: git-env
         image: git-sync:v4.1.0
         imagePullPolicy: IfNotPresent
         name: git-sync
         resources: {}
         securityContext:
           readOnlyRootFilesystem: false
           runAsUser: 65533
         volumeMounts:
         - mountPath: /git
           name: dir
         workingDir: /git
       securityContext:
         fsGroup: 101
       volumes:
       - name: dir
         persistentVolumeClaim:
           claimName: test-pvc
```

**Error output:** 

```
{"logger":"","ts":"2023-11-07 16:25:25.827325","caller":{"file":"main.go","line":1155},"msg":"can't get repo toplevel","error":"Run(git rev-parse --show-toplevel): exit status 128: { stdout: \"\", stderr: \"fatal: not a git repository (or any of the parent directories): .git\" }","path":"/git"}
--
{"logger":"","ts":"2023-11-07 16:25:25.827405","caller":{"file":"main.go","line":1079},"level":0,"msg":"repo directory was empty or failed checks","path":"/git"}
{"logger":"","ts":"2023-11-07 16:25:25.829354","caller":{"file":"main.go","line":784},"msg":"too many failures, aborting","error":"can't wipe unusable root directory: unlinkat /git/.snapshot: read-only file system","failCount":1}
```

I have no idea what this could be connected with. Other containers connect to nfs without problems. If I switch to vmware csi or emptydir - there are no errors.

Can anyone help with ?
