### ISSUE TITLE
exechook working

### ISSUE THREAD

**Issue by abhinavgautam-07** [kubernetes/git-sync#881]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  labels:
    app: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      securityContext:
        fsGroup: 65533
        runAsUser: 65533
      volumes:
        - name: git-secret
          secret:
           secretName: git-creds
           defaultMode: 0400
        - name: content-from-git
          emptyDir: {}
      initContainers:
        - name: setup
          image: XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/platform-config-service:k8s-service-deployment-development-92
          command: ['sh', '-c', 'cp -R /usr/src/app/. /mnt/ && ls -la /mnt/']
          volumeMounts:
            - name: content-from-git
              mountPath: /mnt
      containers:
        - name: git-sync
          securityContext:
            runAsUser: 65533
          image: registry.k8s.io/git-sync/git-sync:v4.0.0
          args:
            - "--ssh"
            - --repo=<git_repo>
            - --depth=10
            - --period=60s
            - --link=current
            - --root=/git
            - --ref=k8s-service-deployment
            - --exechook-command=/bin/sh /git/current/exec_hook.sh
            - --verbose=1000
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: content-from-git
              mountPath: /git
        - name: platform-config-service
          securityContext:
            runAsUser: 0
          image: XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/platform-config-service:k8s-service-deployment-development-92
          command: ["/bin/bash", "/usr/src/app/docker-run.sh", "development", "release-development-92", "7020"]
          volumeMounts:
            - name: content-from-git
              mountPath: /usr/src/app/
          ports:
            - containerPort: 7020
            
```

This my manifest file.

#### What I want to achieve

My main container is `main-app`. When I start the container. It has some source code (along with some config files which are not present on git) at /usr/src/app. What i want to with git-sync is to update the code at /usr/src/app with the latest code. Also i want to run some commands with exechook-command. but it is giving error 

```
{"logger":"exechook","ts":"2024-06-06 12:04:47.250217","caller":{"file":"exechook.go","line":71},"level":0,"msg":"running exechook","hash":"8b100e354e3854dc36af1980835e9a260173b70a","command":"/bin/sh /git/current/exec_hook.sh","timeout":"30s"}
{"logger":"exechook","ts":"2024-06-06 12:04:47.250272","caller":{"file":"exechook.go","line":72},"level":5,"msg":"running command","cwd":"/git/.worktrees/8b100e354e3854dc36af1980835e9a260173b70a","cmd":"\"/bin/sh /git/current/exec_hook.sh\" "}
{"logger":"exechook","ts":"2024-06-06 12:04:47.250672","caller":{"file":"hook.go","line":143},"msg":"hook failed","error":"Run(\"/bin/sh /git/current/exec_hook.sh\" ): fork/exec /bin/sh /git/current/exec_hook.sh: no such file or directory: { stdout: \"\", stderr: \"\" }","hash":"8b100e354e3854dc36af1980835e9a260173b70a","retry":"3s"}
```
But when I exec into the git-sync container and run the command 

`/bin/sh /git/current/exec_hook.sh` . It is working properly.

Can I get some suggestions around. What better config I can have and how to solve this exechook error.
