### ISSUE TITLE
Error when using credentials

### ISSUE THREAD

**Issue by g4s8** [kubernetes/git-sync#91]
When I add `username` and `password` to `git-sync` command it failed with error:
```
ERROR: can't create .netrc file: error setting up git credentials exit status 255: error: could not lock config file //.gitconfig: Permission denied
```

**Comment by stp-ip** [comment]
The permissions don't allow git-sync to create the credentials file.
You can either do the hacky/non-secure way and `runAsUser: 0` or set the permissions of the volume so that git-sync can edit the files.

**Comment by g4s8** [comment]
@stp-ip could you please clarify what permissions I have to set to the volume? It's not very clear how git-sync container works internally. I'm using git-sync in conjunction with https://github.com/box/kube-applier so my `deployment.yaml` looks similar to this:
```yaml
  apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    name: "kube-applier"
    namespace: "kube-system"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: "kube-applier"
      spec:
        containers:
          - name: "kube-applier"
            command:
              - "/kube-applier"
            env:
              - name: "REPO_PATH"
                value: "/git/repo"
              - name: "LISTEN_PORT"
                value: "2020"
              - name: "WHITELIST_PATH"
                value: "/git/repo/k8s"
            image: "g4s8/kube-applier:v0.1.2"
            ports:
              - containerPort: 2020
            volumeMounts:
              - name: "git-repo"
                mountPath: "/git"
          - name: "git-sync"
            command:
              - "/git-sync"
            env:
              - name: "GIT_SYNC_REPO"
                # repo
              - name: "GIT_SYNC_DEST"
                value: "repo"
              - name: "GIT_SYNC_USERNAME"
                valueFrom:
                  secretKeyRef:
                    # username key ref
              - name: "GIT_SYNC_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    # passord key ref
            image: "gcr.io/google_containers/git-sync:v2.0.6"
            ports:
              - containerPort: 2020
            volumeMounts:
              - name: "git-repo"
                mountPath: "/git"
        volumes:
          - name: "git-repo"
            emptyDir: {}

```
