### ISSUE TITLE
On initial sync, all files are in deleted status

### ISSUE THREAD

**Issue by dmfrey** [kubernetes/git-sync#915]
When I setup git-sync, it seems to clone correctly, but when I shell into the container and into the root folder, I only see the symlink directory and worktrees.

Calling `git status` shows all the files as `deleted`. 

What is causing this?

Here's my environment config:

```
env:
    GITSYNC_REPO: git@github.com:some/repo.git
    GITSYNC_REF: main
    GITSYNC_PERIOD: 10s # 1 day
    GITSYNC_ROOT: /tmp/config
    GITSYNC_ADD_USER: "true"
```
