### ISSUE TITLE
V4: GITSYNC_REF or V3: GIT_SYNC_BRANCH

### ISSUE THREAD

**Issue by jorgemgomes** [kubernetes/git-sync#917]
I am experiencing some weird behavior in GitLab CI/CD that I’m not sure if I’m handling correctly.

When I set GITSYNC_REF = CI_COMMIT_REF_NAME (or in V3, GIT_SYNC_BRANCH = CI_COMMIT_REF_NAME), the repository is not cloned unless it's set to the default branch. Does anyone else encounter the same issue when setting the branch to something other than the default branch?

Thanks!

**Comment by thockin** [comment]
v3 has a broken understanding of the relationship between branches and refs (sorry!).  v4 should be saner.

If you're experiencing a problem with v4, I need a simple repro case so I can understand what's happening.  Is CI_COMMIT_REF_NAME a branch or tag or SHA?  Help me set up a failure case so I can deal wiuth it.  I *think* v4 should be able to do anything, as long as fetch-by-SHA is enabled.

**Comment by jorgemgomes** [comment]
If I have a job with this configuration:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName}}-job
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      volumes:
        - name: dbinit
          emptyDir: { }
      initContainers:
        - image: registry.k8s.io/git-sync:v3.1.6
          name: git-data
          volumeMounts:
            - name: dbinit
              mountPath: /tmp/repo
          env:
            - name: GIT_SYNC_REPO
              value: #######
            - name: GIT_SYNC_ROOT
              value: /tmp/repo
            - name: GIT_SYNC_DEST
              value: "project"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: gitlabtokenusername
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: gitlabtokenpassword
          securityContext:
            runAsUser: 0
      containers:
        - image: #######
          name: dbinit          
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: dbinit
              mountPath: /deployments
              subPath: project/dbinit
          command: [ "/bin/sh", "-c" ]
          args:
            - ls -l /deployments;
      imagePullSecrets:
        - name: {{ .Values.appName }}-gitlab-docker-auth
      restartPolicy: OnFailure
  backoffLimit: 4
```

Output of ls -l /deployments is OK:

total 4
drwxr-xr-x 2 root root  54 Aug 13 07:27 changesets
-rw-r--r-- 1 root root 378 Aug 13 07:27 db.changelog-master.xml


If I have a job with this configuration:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName}}-job
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      volumes:
        - name: dbinit
          emptyDir: { }
      initContainers:
        - image: registry.k8s.io/git-sync/git-sync:v4.2.4
          name: git-data
          volumeMounts:
            - name: dbinit
              mountPath: /tmp/repo
          env:
            - name: GITSYNC_REF
              value: "feature/EUDD-3264-ci-cd-config"
            - name: GITSYNC_REPO
              value: #######
            - name: GITSYNC_ROOT
              value: /tmp/repo
            - name: GITSYNC_DEST
              value: "project"
            - name: GITSYNC_ONE_TIME
              value: "true"
            - name: GITSYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: gitlabtokenusername
            - name: GITSYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-secrets
                  key: gitlabtokenpassword
          securityContext:
            runAsUser: 0
      containers:
        - image: #######
          name: dbinit
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: dbinit
              mountPath: /deployments
              subPath: project/dbinit
          command: [ "/bin/sh", "-c" ]
          args:
            - ls -l /deployments;
      imagePullSecrets:
        - name: {{ .Values.appName }}-gitlab-docker-auth
      restartPolicy: OnFailure
  backoffLimit: 4

```

Output of ls -l /deployments is not OK:

total 0
