### ISSUE TITLE
Git-Sync with ssh

### ISSUE THREAD

**Issue by anilsati79** [kubernetes/git-sync#920]
I have tried all settings as provided in documentation, but no luck.
Just getting same redundant error.

Host key verification failed.\\r\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\" }"  
I0916 00:13:01.273475      13 main.go:535]  "level"=0 "msg"="waiting before retrying"  "waitTime"=0

It seems while making ssh connection with git, path for key is not taken from ssh_key_file parameter.

**Comment by e3oroush** [comment]
I had the same problem with the latest version of `git-sync`. After checking the logs and debugging, I found out there's a problem of git client not able to read from the provided ssh-keys from `/etc/git-secret` directory. The solution I came up with to add the following environment variable, so guide the git client to read from this directory:
```bash
export GIT_SSH_COMMAND="ssh -i /etc/git-secret/ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
```
The complete example based on the provided [docs](https://github.com/kubernetes/git-sync/blob/master/docs/ssh.md) is as follows:
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  selector:
    matchLabels:
      demo: git-sync
  template:
    metadata:
      labels:
        demo: git-sync
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 0400
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync:v4.0.0
        args:
         - "--repo=git@github.com:torvalds/linux"
         - "--depth=1"
        env:
            # I don't know why I had to set this env. It took me a long time to but I guess there's a bug here
            - name: GIT_SSH_COMMAND
              value: "ssh -i /etc/git-secret/ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
      securityContext:
        fsGroup: 65533 # to make SSH key readable
```

My guess it's a bug that'll hopefully fixed in the near future. But this worked for me.

**Comment by thockin** [comment]
I am sorry, I don't know what the problem here is.  I just tried to repoduce it and, while I found a bug in the docs (https://github.com/kubernetes/git-sync/pull/921), it is not related to this.

I literally just ran this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  selector:
    matchLabels:
      demo: git-sync
  template:
    metadata:
      labels:
        demo: git-sync
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 0400
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v4.2.4
        args:
         - "--repo=git@github.com:kubernetes/git-sync"
         - "--depth=1"
         - "--ssh-known-hosts=false"
        securityContext:
          runAsUser: 65533 # git-sync user
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
          readOnly: true
      securityContext:
        fsGroup: 65533 # to make SSH key readable
```

Can you please try that and see if it doesn't work?  If not, please post the EXACT yaml you used and the full logs with `-v6`
